/******************************************************************************
* Programmer: Yeji Chung													  *
* Class: CptS 121; Lab Section 16                                             *
* Programming Assignment: PA3 C File Processing with Functions                *
* Date:  9/19/2016                                                            *
*                                                                             *
* Description: This program analyze a sentence as following parts.            *
*              1. ascii code of each character in the sentence.               *
*              2. The number of line in the sentence.                         *
*              3. The number of vowels in the sentence.                       *
*              4. The number of digits in the sentence.                       *
*              5. The number of alphabets in the sentence.                    *
*              6. The number of lower case alphabets in the sentence.         *
*              7. The number of upper case alphabets in the sentence.         *
*              8. The number of spaces in the sentence.                       *
*			   9. The number of alphabets and digits in the sentence.		  *
*			   10. The number of punctuations in the sentence.				  *
*																			  *
*              Inputs: A sentence										      *
*              Computations: analyze the sentence.                            *
*              Outputs: above list 1~10								          *
*                                                                             *
******************************************************************************/
#include"header.h"
int main(void)
{
	
	FILE*infile = NULL, *outfile_status = NULL, *outfile_ascii = NULL;
	char read_character1 = '\0',
		read_character2 = '\0',
		read_character3 = '\0',
		read_character4 = '\0',
		read_character5 = '\0',
		read_character6 = '\0',
		read_character7 = '\0',
		read_character8 = '\0',
		read_character9 = '\0',
		read_character10 = '\0',
		header1[] = "Number Line : ",
		header2[] = "Number Vowels : ", 
		header3[] = "Number Digits : ", 
		header4[] = "Number Alphas : ", 
		header5[] = "Number Lowers : ", 
		header6[] = "Number Uppers : ", 
		header7[] = "Number Spaces : ", 
		header8[] = "Number Alnums : ",
		header9[] = "Number Puncts : ";

	int ascii_num1 = 0, ascii_num2 = 0,
		ascii_num3 = 0, ascii_num4 = 0,
		ascii_num5 = 0, ascii_num6 = 0,
		ascii_num7 = 0, ascii_num8 = 0,
		ascii_num9 = 0, ascii_num10 = 0,
		current_number_lines = 1,
		current_number_vowels = 0,
		current_number_digits = 0,
		current_number_alphas = 0,
		current_number_lowers = 0,
		current_number_uppers = 0,
		current_number_spaces = 0,
		current_number_alnums = 0,
		current_number_puncts = 0;

	//Opens an input file input.dat for reading;
	infile = open_input_file();

	//Opens an output file output_stats.dat for writing all data generated by print_stats();
	outfile_status= fopen("output_status.dat", "w");

	//Opens an output file output_ascii.dat for writing all ascii values of each character;	
	outfile_ascii = fopen("ourput_ascii.dat", "w");

	//Checks to see if the files were opened successfully
	fprintf(outfile_status, "open seccessfully!\n");
	fprintf(outfile_ascii, "open seccessfully!\n");

	//Reads one character at a time from the input file(input.dat), until all 10 characters have been read; For each character that is read in,
	read_character1 = read_character(infile);
	read_character2 = read_character(infile);
	read_character3 = read_character(infile);
	read_character4 = read_character(infile);
	read_character5 = read_character(infile);
	read_character6 = read_character(infile);
	read_character7 = read_character(infile);
	read_character8 = read_character(infile);
	read_character9 = read_character(infile);
	read_character10 = read_character(infile);

	//-its corresponding ASCII value should be printed to the output file, output_ascii.dat; Hint: use the print_int() function to print the ASCII values;
	//Read 10 character, and determine asciivalue
	ascii_num1 = determine_ascii_value(read_character1);
	ascii_num2 = determine_ascii_value(read_character2);
	ascii_num3 = determine_ascii_value(read_character3);
	ascii_num4 = determine_ascii_value(read_character4);
	ascii_num5 = determine_ascii_value(read_character5);
	ascii_num6 = determine_ascii_value(read_character6);
	ascii_num7 = determine_ascii_value(read_character7);
	ascii_num8 = determine_ascii_value(read_character8);
	ascii_num9 = determine_ascii_value(read_character9);
	ascii_num10 = determine_ascii_value(read_character10);

	// print 10 character to output_ascii.dat
	print_int(outfile_ascii, ascii_num1);	
	print_int(outfile_ascii, ascii_num2);
	print_int(outfile_ascii, ascii_num3);
	print_int(outfile_ascii, ascii_num4);
	print_int(outfile_ascii, ascii_num5);
	print_int(outfile_ascii, ascii_num6);
	print_int(outfile_ascii, ascii_num7);
	print_int(outfile_ascii, ascii_num8);
	print_int(outfile_ascii, ascii_num9);
	print_int(outfile_ascii, ascii_num10);

	//Prints the number of lines in the file to output_stats.dat after get result of the number of line;
	current_number_lines = number_lines(read_character1, current_number_lines);
	current_number_lines = number_lines(read_character2, current_number_lines);
	current_number_lines = number_lines(read_character3, current_number_lines);
	current_number_lines = number_lines(read_character4, current_number_lines);
	current_number_lines = number_lines(read_character5, current_number_lines);
	current_number_lines = number_lines(read_character6, current_number_lines);
	current_number_lines = number_lines(read_character7, current_number_lines);
	current_number_lines = number_lines(read_character8, current_number_lines);
	current_number_lines = number_lines(read_character9, current_number_lines);
	current_number_lines = number_lines(read_character10, current_number_lines);
	
	print_stats(outfile_status, header1, current_number_lines);

	//Prints the number of vowels in the file to output_stats.dat after get result of the number of vowels;
	current_number_vowels = number_vowels(read_character1, current_number_vowels);
	current_number_vowels = number_vowels(read_character2, current_number_vowels);
	current_number_vowels = number_vowels(read_character3, current_number_vowels);
	current_number_vowels = number_vowels(read_character4, current_number_vowels);
	current_number_vowels = number_vowels(read_character5, current_number_vowels);
	current_number_vowels = number_vowels(read_character6, current_number_vowels);
	current_number_vowels = number_vowels(read_character7, current_number_vowels);
	current_number_vowels = number_vowels(read_character8, current_number_vowels);
	current_number_vowels = number_vowels(read_character9, current_number_vowels);
	current_number_vowels = number_vowels(read_character10, current_number_vowels);

	print_stats(outfile_status, header2, current_number_vowels);

	//Prints the number of digits in the file to output_stats.dat after get result of the number of digits;
	current_number_digits = number_digits(read_character1, current_number_digits);
	current_number_digits = number_digits(read_character2, current_number_digits);
	current_number_digits = number_digits(read_character3, current_number_digits);
	current_number_digits = number_digits(read_character4, current_number_digits);
	current_number_digits = number_digits(read_character5, current_number_digits);
	current_number_digits = number_digits(read_character6, current_number_digits);
	current_number_digits = number_digits(read_character7, current_number_digits);
	current_number_digits = number_digits(read_character8, current_number_digits);
	current_number_digits = number_digits(read_character9, current_number_digits);
	current_number_digits = number_digits(read_character10, current_number_digits);

	print_stats(outfile_status, header3, current_number_digits);

	//Prints the number of alpha characters in the file to output_stats.dat after get result of the number of alphas;
	current_number_alphas = number_alphas(read_character1, current_number_alphas);
	current_number_alphas = number_alphas(read_character2, current_number_alphas);
	current_number_alphas = number_alphas(read_character3, current_number_alphas);
	current_number_alphas = number_alphas(read_character4, current_number_alphas);
	current_number_alphas = number_alphas(read_character5, current_number_alphas);
	current_number_alphas = number_alphas(read_character6, current_number_alphas);
	current_number_alphas = number_alphas(read_character7, current_number_alphas);
	current_number_alphas = number_alphas(read_character8, current_number_alphas);
	current_number_alphas = number_alphas(read_character9, current_number_alphas);
	current_number_alphas = number_alphas(read_character10, current_number_alphas);

	print_stats(outfile_status, header4, current_number_alphas);

	//Prints the number of lowercase characters in the file to output_stats.dat after get result of the number of lowers;
	current_number_lowers = number_lowers(read_character1, current_number_lowers);
	current_number_lowers = number_lowers(read_character2, current_number_lowers);
	current_number_lowers = number_lowers(read_character3, current_number_lowers);
	current_number_lowers = number_lowers(read_character4, current_number_lowers);
	current_number_lowers = number_lowers(read_character5, current_number_lowers);
	current_number_lowers = number_lowers(read_character6, current_number_lowers);
	current_number_lowers = number_lowers(read_character7, current_number_lowers);
	current_number_lowers = number_lowers(read_character8, current_number_lowers);
	current_number_lowers = number_lowers(read_character9, current_number_lowers);
	current_number_lowers = number_lowers(read_character10, current_number_lowers);

	print_stats(outfile_status, header5, current_number_lowers);

	//Prints the number of uppercase characters in the file to output_stats.dat after get result of the number of uppers;
	current_number_uppers = number_uppers(read_character1, current_number_uppers);
	current_number_uppers = number_uppers(read_character2, current_number_uppers);
	current_number_uppers = number_uppers(read_character3, current_number_uppers);
	current_number_uppers = number_uppers(read_character4, current_number_uppers);
	current_number_uppers = number_uppers(read_character5, current_number_uppers);
	current_number_uppers = number_uppers(read_character6, current_number_uppers);
	current_number_uppers = number_uppers(read_character7, current_number_uppers);
	current_number_uppers = number_uppers(read_character8, current_number_uppers);
	current_number_uppers = number_uppers(read_character9, current_number_uppers);
	current_number_uppers = number_uppers(read_character10, current_number_uppers);

	print_stats(outfile_status, header6, current_number_uppers);

	//Prints the number of space characters in the file to output_stats.dat after get result of the number of spaces;
	current_number_spaces = number_spaces(read_character1, current_number_spaces);
	current_number_spaces = number_spaces(read_character2, current_number_spaces);
	current_number_spaces = number_spaces(read_character3, current_number_spaces);
	current_number_spaces = number_spaces(read_character4, current_number_spaces);
	current_number_spaces = number_spaces(read_character5, current_number_spaces);
	current_number_spaces = number_spaces(read_character6, current_number_spaces);
	current_number_spaces = number_spaces(read_character7, current_number_spaces);
	current_number_spaces = number_spaces(read_character8, current_number_spaces);
	current_number_spaces = number_spaces(read_character9, current_number_spaces);
	current_number_spaces = number_spaces(read_character10, current_number_spaces);

	print_stats(outfile_status, header7, current_number_spaces);

	//Prints the number of alphanumeric characters in the file to output_stats.dat after get result of the number of alnums;
	current_number_alnums = number_alnums(read_character1, current_number_alnums);
	current_number_alnums = number_alnums(read_character2, current_number_alnums);
	current_number_alnums = number_alnums(read_character3, current_number_alnums);
	current_number_alnums = number_alnums(read_character4, current_number_alnums);
	current_number_alnums = number_alnums(read_character5, current_number_alnums);
	current_number_alnums = number_alnums(read_character6, current_number_alnums);
	current_number_alnums = number_alnums(read_character7, current_number_alnums);
	current_number_alnums = number_alnums(read_character8, current_number_alnums);
	current_number_alnums = number_alnums(read_character9, current_number_alnums);
	current_number_alnums = number_alnums(read_character10, current_number_alnums);

	print_stats(outfile_status, header8, current_number_alnums);

	//Prints the number of punctuation characters in the file to output_stats.dat after get result of the number of puncts;
	current_number_puncts = number_puncts(read_character1, current_number_puncts);
	current_number_puncts = number_puncts(read_character2, current_number_puncts);
	current_number_puncts = number_puncts(read_character3, current_number_puncts);
	current_number_puncts = number_puncts(read_character4, current_number_puncts);
	current_number_puncts = number_puncts(read_character5, current_number_puncts);
	current_number_puncts = number_puncts(read_character6, current_number_puncts);
	current_number_puncts = number_puncts(read_character7, current_number_puncts);
	current_number_puncts = number_puncts(read_character8, current_number_puncts);
	current_number_puncts = number_puncts(read_character9, current_number_puncts);
	current_number_puncts = number_puncts(read_character10, current_number_puncts);

	print_stats(outfile_status, header9, current_number_puncts);

	//Closes all opened files;
	fclose(infile);
	fclose(outfile_ascii);
	fclose(outfile_status);

	return 0;
}